name: Build and Deploy React App to GitHub Pages
on:
    push:
        branches: [staging]
    pull_request:
        branches: [staging]
jobs:
    build-and-deploy:
         name: Deploy to Server on staging branch
        runs-on: ubuntu-latest

        steps:
             - name: Get the latest code
              uses: actions/checkout@v2.3.2
            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEV_REMOTE_HOST}}
                  key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
                  username: ${{ secrets.REMOTE_USER }}
                  script: |
                      npm run deploy
                      git pull origin staging
